config/routes.rb
Rails.application.routes.draw do
  resources :comentarios
  resources :noticia
  resources :welcome

  get 'welcome/userShow/:id' => 'welcome#userShow', :as => :userShow
  get 'welcome/show/:id' => 'welcome#show', :as => :show
  get 'welcome/index'
  get 'noticia/userShow'
  get 'welcome/userShow'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comentario.rb
class Comentario < ApplicationRecord
	belongs_to :noticium
	validates :usuario, :presence => true
	validates :contenido, :presence => true
end

app/models/noticium.rb
class Noticium < ApplicationRecord
	has_many :comentarios, dependent: :destroy
	default_scope { order('created_at DESC')}
	validates :titulo, :presence => true
	validates :bajada, :presence => true
	validates :cuerpo, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario was successfully created.' }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:contenido, :usuario, :noticia)
    end
end

app/controllers/noticia_controller.rb
class NoticiaController < ApplicationController
  before_action :set_noticium, only: [:show, :edit, :update, :destroy]


  # GET /noticia
  # GET /noticia.json
  def index
    @noticia = Noticium.all
  end

  # GET /noticia/1
  # GET /noticia/1.json
  def show
  end

  # GET /noticia/new
  def new
    @noticium = Noticium.new
  end

  # GET /noticia/1/edit
  def edit
  end

  # POST /noticia
  # POST /noticia.json
  def create
    @noticium = Noticium.new(noticium_params)

    respond_to do |format|
      if @noticium.save
        format.html { redirect_to @noticium, notice: 'Noticium was successfully created.' }
        format.json { render :show, status: :created, location: @noticium }
      else
        format.html { render :new }
        format.json { render json: @noticium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /noticia/1
  # PATCH/PUT /noticia/1.json
  def update
    respond_to do |format|
      if @noticium.update(noticium_params)
        format.html { redirect_to @noticium, notice: 'Noticium was successfully updated.' }
        format.json { render :show, status: :ok, location: @noticium }
      else
        format.html { render :edit }
        format.json { render json: @noticium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /noticia/1
  # DELETE /noticia/1.json
  def destroy
    @noticium.destroy
    respond_to do |format|
      format.html { redirect_to noticia_url, notice: 'Noticium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_noticium
      @noticium = Noticium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def noticium_params
      params.require(:noticium).permit(:titulo, :bajada, :cuerpo, :nComentarios)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :set_noticium, only: [:show, :edit, :update, :destroy, :userShow]

    # GET /noticia
  # GET /noticia.json
  def index
    @ultimas = Noticium.first(10)
    @noticia = Noticium.all
  end

  def userShow

  end

  def show
    
  end


  # GET /noticia/new
  def new
    @noticium = Noticium.new
  end

  # GET /noticia/1/edit
  def edit
  end

  # POST /noticia
  # POST /noticia.json
  def create
    @noticium = Noticium.new(noticium_params)

    respond_to do |format|
      if @noticium.save
        format.html { redirect_to @noticium, notice: 'Noticium was successfully created.' }
        format.json { render :show, status: :created, location: @noticium }
      else
        format.html { render :new }
        format.json { render json: @noticium.errors, status: :unprocessable_entity }
      end
    end
  end


# PATCH/PUT /noticia/1
  # PATCH/PUT /noticia/1.json
  def update
    respond_to do |format|
      if @noticium.update(noticium_params)
        format.html { redirect_to @noticium, notice: 'Noticium was successfully updated.' }
        format.json { render :userShow, status: :ok, location: @noticium }
      else
        format.html { render :edit }
        format.json { render json: @noticium.errors, status: :unprocessable_entity }
      end
    end
  end



# Use callbacks to share common setup or constraints between actions.
  def set_noticium
    @noticium = Noticium.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def noticium_params
    params.require(:noticium).permit(:titulo, :bajada, :cuerpo, :nComentarios)
  end

  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/noticia_helper.rb
module NoticiaHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comentarios/_form.html.erb
<%= form_for(comentario) do |f| %>
  <% if comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% comentario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contenido %>
    <%= f.text_field :contenido %>
  </div>

  <div class="field">
    <%= f.label :usuario %>
    <%= f.text_field :usuario %>
  </div>

  <div class="field">
    <%= f.label :noticia %>
    <%= f.number_field :noticia %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Contenido</th>
      <th>Usuario</th>
      <th>Noticia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.contenido %></td>
        <td><%= comentario.usuario %></td>
        <td><%= comentario.noticia %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form', comentario: @comentario %>


<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contenido:</strong>
  <%= @comentario.contenido %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @comentario.usuario %>
</p>

<p>
  <strong>Noticia:</strong>
  <%= @comentario.noticia %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tarea</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/noticia/_form.html.erb
<%= form_for(noticium) do |f| %>
  <% if noticium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(noticium.errors.count, "error") %> prohibited this noticium from being saved:</h2>

      <ul>
      <% noticium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %>
    <%= f.text_field :titulo %>
  </div>

  <div class="field">
    <%= f.label :bajada %>
    <%= f.text_field :bajada %>
  </div>

  <div class="field">
    <%= f.label :cuerpo %>
    <%= f.text_field :cuerpo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/noticia/edit.html.erb
<h1>Editing Noticium</h1>

<%= render 'form', noticium: @noticium %>

<%= link_to 'Show', @noticium %> |
<%= link_to 'Back', noticia_path %>

app/views/noticia/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Usuario', welcome_index_path %>

<h1>Listado de Noticias</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Bajada</th>
      <th>Cuerpo</th>
      <th>Fecha de Publicación</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @noticia.each do |noticium| %>
      <tr>
        <td><%= noticium.titulo %></td>
        <td><%= noticium.bajada %></td>
        <td><%= noticium.cuerpo %></td>
        <td><%= noticium.created_at %></td>
        <td><%= link_to 'Show', noticium %></td>
        <td><%= link_to 'Edit', edit_noticium_path(noticium) %></td>
        <td><%= link_to 'Destroy', noticium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Noticia', new_noticium_path %>

app/views/noticia/new.html.erb
<h1>Nueva noticia</h1>

<%= render 'form', noticium: @noticium %>

<%= link_to 'Back', noticia_path %>

app/views/noticia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @noticium.titulo %>
</p>

<p>
  <strong>Bajada:</strong>
  <%= @noticium.bajada %>
</p>

<p>
  <strong>Cuerpo:</strong>
  <%= @noticium.cuerpo %>
</p>

<p>
  <strong>Ncomentarios:</strong>
  <%= @noticium.nComentarios %>
</p>

<%= link_to 'Write a comment', new_comentario_path %>

<%= link_to 'Edit', edit_noticium_path(@noticium) %> |
<%= link_to 'Back', noticia_path %>

app/views/welcome/index.html.erb
<%= link_to 'Administrador', noticia_path %>

<h1>¡¡ Bienvenido a tu página favorita de noticias !!</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Bajada</th>
      <th>Cuerpo</th>
      <th>Fecha de Publicación</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ultimas.each do |noticium| %>
      <tr>
        <td><%= noticium.titulo %></td>
        <td><%= noticium.bajada %></td>
        <td><%= noticium.cuerpo %></td>
        <td><%= noticium.created_at %></td>
        <td><%= link_to 'Show', noticium %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/welcome/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @noticium.titulo %>
</p>

<p>
  <strong>Bajada:</strong>
  <%= @noticium.bajada %>
</p>

<p>
  <strong>Cuerpo:</strong>
  <%= @noticium.cuerpo %>
</p>


<p>
  <strong>Ncomentarios:</strong>
  <%= @noticium.nComentarios %>
</p>

<%= link_to 'Back', welcome_index_path %>

app/views/welcome/userShow.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @noticium.titulo %>
</p>

<p>
  <strong>Bajada:</strong>
  <%= @noticium.bajada %>
</p>

<p>
  <strong>Cuerpo:</strong>
  <%= @noticium.cuerpo %>
</p>


<p>
  <strong>Ncomentarios:</strong>
  <%= @noticium.nComentarios %>
</p>

<%= link_to 'Back', root %>